ERROR - 2024-05-06 04:31:01 --> mysqli_sql_exception: Table 'ci4.books' doesn't exist in C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#7 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Controllers\Books.php(19): App\Models\BooksModel->getBuku()
#8 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\PC18\Pemweb-2\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\P...')
#13 {main}
CRITICAL - 2024-05-06 04:31:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'ci4.books' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 2 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBuku()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 04:31:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'ci4.books' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `books`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `books`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 4 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBuku()
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 04:31:01 --> [Caused by] mysqli_sql_exception: Table 'ci4.books' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `books`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `books`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `books`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 5 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBuku()
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
ERROR - 2024-05-06 04:31:13 --> mysqli_sql_exception: Table 'ci4.books' doesn't exist in C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
#7 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Controllers\Books.php(19): App\Models\BooksModel->getBuku()
#8 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\PC18\Pemweb-2\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\P...')
#13 {main}
CRITICAL - 2024-05-06 04:31:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'ci4.books' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 2 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBuku()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 04:31:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'ci4.books' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `books`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `books`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 4 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBuku()
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 04:31:13 --> [Caused by] mysqli_sql_exception: Table 'ci4.books' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `books`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `books`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `books`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 5 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\BooksModel.php(17): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBuku()
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:13:02 --> ErrorException: Undefined variable $crsf_field
in APPPATH\Views\books\create.php on line 9.
 1 APPPATH\Views\books\create.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $crsf_field', 'C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\app\\Views\\books\\create.php', 9)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\app\\Views\\books\\create.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('books/create', [], true)
 5 APPPATH\Controllers\Books.php(45): view('books/create', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:13:55 --> ErrorException: Undefined variable $crsf_field
in APPPATH\Views\books\create.php on line 9.
 1 APPPATH\Views\books\create.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $crsf_field', 'C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\app\\Views\\books\\create.php', 9)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\app\\Views\\books\\create.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('books/create', [], true)
 5 APPPATH\Controllers\Books.php(45): view('books/create', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
INFO - 2024-05-06 05:28:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:28:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:29:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:29:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:29:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:29:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:29:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:29:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:29:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:31:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:31:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:31:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:31:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:31:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:31:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:32:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:32:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:33:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:33:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-05-06 05:36:09 --> Error: Call to undefined method CodeIgniter\View\View::extends()
in APPPATH\Views\books\create.php on line 1.
 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('books/create', [], true)
 4 APPPATH\Controllers\Books.php(54): view('books/create', [...])
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->create()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
ERROR - 2024-05-06 05:36:32 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Controllers\Books.php(66): CodeIgniter\BaseModel->save(Array)
#9 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\Users\PC18\Pemweb-2\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\P...')
#14 {main}
CRITICAL - 2024-05-06 05:36:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:36:32 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:36:32\', \'2024-05-06 05:36:32\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:36:32\', \'2024-05-06 05:36:32\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:36:32 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:36:32\', \'2024-05-06 05:36:32\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:36:32\', \'2024-05-06 05:36:32\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:36:32\', \'2024-05-06 05:36:32\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
ERROR - 2024-05-06 05:37:57 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Controllers\Books.php(66): CodeIgniter\BaseModel->save(Array)
#9 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\Users\PC18\Pemweb-2\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\P...')
#14 {main}
CRITICAL - 2024-05-06 05:37:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:37:57 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:37:57\', \'2024-05-06 05:37:57\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:37:57\', \'2024-05-06 05:37:57\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:37:57 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:37:57\', \'2024-05-06 05:37:57\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:37:57\', \'2024-05-06 05:37:57\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:37:57\', \'2024-05-06 05:37:57\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
ERROR - 2024-05-06 05:38:00 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Controllers\Books.php(66): CodeIgniter\BaseModel->save(Array)
#9 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\Users\PC18\Pemweb-2\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\P...')
#14 {main}
CRITICAL - 2024-05-06 05:38:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:38:00 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:00\', \'2024-05-06 05:38:00\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:00\', \'2024-05-06 05:38:00\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:38:00 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:00\', \'2024-05-06 05:38:00\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:00\', \'2024-05-06 05:38:00\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'komik\', \'komik\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:00\', \'2024-05-06 05:38:00\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
ERROR - 2024-05-06 05:38:05 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Controllers\Books.php(66): CodeIgniter\BaseModel->save(Array)
#9 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\Users\PC18\Pemweb-2\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\P...')
#14 {main}
CRITICAL - 2024-05-06 05:38:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:38:05 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:05\', \'2024-05-06 05:38:05\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:05\', \'2024-05-06 05:38:05\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:38:05 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:05\', \'2024-05-06 05:38:05\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:05\', \'2024-05-06 05:38:05\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:05\', \'2024-05-06 05:38:05\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
ERROR - 2024-05-06 05:38:40 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Controllers\Books.php(66): CodeIgniter\BaseModel->save(Array)
#9 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\Users\PC18\Pemweb-2\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\P...')
#14 {main}
CRITICAL - 2024-05-06 05:38:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:38:40 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:40\', \'2024-05-06 05:38:40\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:40\', \'2024-05-06 05:38:40\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:38:40 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:40\', \'2024-05-06 05:38:40\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:40\', \'2024-05-06 05:38:40\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:38:40\', \'2024-05-06 05:38:40\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
ERROR - 2024-05-06 05:43:07 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Controllers\Books.php(66): CodeIgniter\BaseModel->save(Array)
#9 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\Users\PC18\Pemweb-2\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\P...')
#14 {main}
CRITICAL - 2024-05-06 05:43:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:43:07 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:07\', \'2024-05-06 05:43:07\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:07\', \'2024-05-06 05:43:07\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:43:07 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:07\', \'2024-05-06 05:43:07\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:07\', \'2024-05-06 05:43:07\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:07\', \'2024-05-06 05:43:07\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
ERROR - 2024-05-06 05:43:36 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Controllers\Books.php(66): CodeIgniter\BaseModel->save(Array)
#9 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\Users\PC18\Pemweb-2\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\P...')
#14 {main}
CRITICAL - 2024-05-06 05:43:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:43:36 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:36\', \'2024-05-06 05:43:36\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:36\', \'2024-05-06 05:43:36\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:43:36 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:36\', \'2024-05-06 05:43:36\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:36\', \'2024-05-06 05:43:36\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:36\', \'2024-05-06 05:43:36\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
ERROR - 2024-05-06 05:43:38 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Controllers\Books.php(66): CodeIgniter\BaseModel->save(Array)
#9 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\Users\PC18\Pemweb-2\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\P...')
#14 {main}
CRITICAL - 2024-05-06 05:43:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:43:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:38\', \'2024-05-06 05:43:38\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:38\', \'2024-05-06 05:43:38\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:43:38 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:38\', \'2024-05-06 05:43:38\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:38\', \'2024-05-06 05:43:38\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:43:38\', \'2024-05-06 05:43:38\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(66): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
ERROR - 2024-05-06 05:45:22 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\Users\PC18\Pemweb-2\project-root\project-root\app\Controllers\Books.php(63): CodeIgniter\BaseModel->save(Array)
#9 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\Users\PC18\Pemweb-2\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\Users\PC18\Pemweb-2\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\P...')
#14 {main}
CRITICAL - 2024-05-06 05:45:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(63): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:45:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:45:22\', \'2024-05-06 05:45:22\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:45:22\', \'2024-05-06 05:45:22\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(63): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 05:45:22 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:45:22\', \'2024-05-06 05:45:22\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:45:22\', \'2024-05-06 05:45:22\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 05:45:22\', \'2024-05-06 05:45:22\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(63): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\PC18\\Pemweb-2\\project-root\\project-root\\public\\index.php')
INFO - 2024-05-06 05:57:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:57:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 05:58:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 12:07:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-06 12:07:08 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `bo...', 0)
#1 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\Users\Vian\Downloads\project-root\project-root\app\Controllers\Books.php(58): CodeIgniter\BaseModel->save(Array)
#9 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->save()
#10 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\Users\Vian\Downloads\project-root\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\Users\Vian\Downloads\project-root\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\Vian\\D...')
#14 {main}
CRITICAL - 2024-05-06 12:07:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Books.php(58): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\Vian\\Downloads\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 12:07:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 12:07:08\', \'2024-05-06 12:07:08\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 12:07:08\', \'2024-05-06 12:07:08\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Books.php(58): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\Vian\\Downloads\\project-root\\project-root\\public\\index.php')
CRITICAL - 2024-05-06 12:07:08 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 12:07:08\', \'2024-05-06 12:07:08\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 12:07:08\', \'2024-05-06 12:07:08\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (\'p\', \'p\', \'p\', \'p\', \'p\', \'2024-05-06 12:07:08\', \'2024-05-06 12:07:08\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `slug`, `penulis`, `penerbit`, `sampul`, `created_at`, `updated_at`) VALUES (:judul:, :slug:, :penulis:, :penerbit:, :sampul:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Books.php(58): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->save()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\Vian\\Downloads\\project-root\\project-root\\public\\index.php')
INFO - 2024-05-06 12:07:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 12:07:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-06 12:07:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
